fix: inference regression and pin `physicalai` library (#644)
* fix: lock the physicalai library by a specific commit

When using a branch as a ref uv won't automatically fetch the latest
version when syncing with `uv sync`, and this leads to bugs that are
hard to detect.

For now we will lock the library to a specific commit until we've
published it to pypy, at which point we will constraint to some version.

* fix: normalize model action chunks for inference

Inference was failing in RobotControlWorker with:

```
TypeError: 'float' object is not iterable
```

The failure happened due to a change in the return type of
`predict_action_chunk`.

* fix: update library lockfile